version: '3.8'
services:
  app:
    build: .
    container_name: easy-market-server
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm run start:prod

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ecommerce_owner
      POSTGRES_PASSWORD: gatostem123
      POSTGRES_DB: ecommerce
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
